###############################################################################
# Sepsis + COPD comorbidity analysis — myeloid subset refinement analysis
# File: 03_myeloid_subclustering.R (formerly 03_myeloid_subsets.R)
#
# Purpose: the main annotation mixes myeloid (monocyte/macrophage/DC) together (Monocyte 10 clusters + DC 2 clusters),
#   this script subclusters the myeloid compartment separately and subdivides it into:
#         CD14_Mono   classical monocyte (CD14+)
#         CD16_Mono   non-classical monocyte (FCGR3A/CD16+)
#         Macrophage  macrophage-like (CD68/CD163/MRC1)
#         cDC         conventional dendritic cell (CD1C/CLEC10A/HLA-DQA1)
#         pDC         plasmacytoid dendritic cell (LILRA4/CLEC4C/IL3RA/TCF4)
#       and identifies differentially enriched subsets across the five groups
#       (Healthy/Infection_Control/COPD/Sepsis/Sepsis_Pneumonia) to answer
#       "which monocyte/macrophage states are disease-specific or comorbidity-shared".
#
# Marker genes have been verified: all are present in the original gene lists of
#   GSE167363/GSE175453/GSE279452/GSE151263. (Note: the raw file has them, but not necessarily
#   after min.cells=3 filtering, so the automatic skip fallback is still kept.)
#
# Workflow:
#   Step 1: load the integrated annotated object
#   Step 2: extract the myeloid compartment (cell_type == Monocyte/DC)
#   Step 3: subclustering + sub-annotation (resolution raised to 1.0)
#   Step 4: visualization validation (UMAP + DotPlot)
#   Step 5: five-group proportions + Ro/e
#   Step 6: differential subset identification across groups
#   Step 7: save
#
# Prerequisite: 01_assemble_blood_integrated.R (formerly 01_path1_blood_blood_merge.R) has been run
#               to generate path1_sepsis_copd_integrated.rds
###############################################################################

# Auto-locate this script's directory and find 00_config.R in the same directory (no need to change this path locally or on the server)
.this_file <- tryCatch(rstudioapi::getSourceEditorContext()$path, error = function(e) "")
if (.this_file == "" || !file.exists(.this_file)) {
  .f <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(.f) > 0) .this_file <- sub("^--file=", "", .f[1])
}
SCRIPT_DIR  <- dirname(.this_file)
config_file <- file.path(SCRIPT_DIR, "00_config.R")
if (!file.exists(config_file)) stop("Cannot find 00_config.R: ", config_file)
source(config_file)

cat("\n==============================================================\n")
cat("Myeloid subset refinement analysis (Monocyte / Macrophage / DC subclustering)\n")
cat("==============================================================\n")

## =========================================================================
## Step 1: load the integrated annotated object
## =========================================================================

cat("\n===== Step 1: load the integrated annotated object =====\n")

# If 01_path1 has been run in this session and merged carries cell_type, reuse it directly; otherwise read the RDS
if (!exists("merged")) {
  # Candidate file names (the Step 3 checkpoint merged_integrated.rds lacks cell_type and needs re-annotation)
  candidates <- c("merged_integrated.rds", "path1_sepsis_copd_integrated.rds")
  exist_idx <- which(file.exists(file.path(out_dir, candidates)))
  if (length(exist_idx) == 0) {
    stop("Cannot find the integrated object RDS, please confirm the file name")
  }
  merged <- readRDS(file.path(out_dir, candidates[exist_idx[1]]))
}

# Determine whether the main annotation cell_type is "clean". Note: the old read_scp548 stored
# the SCP548 built-in author annotation Cell_Type (Mono/DC/T/NK/B/Megakaryocyte) into the cell_type column,
# while the other datasets (167363/175453/279452/151263) are NA — causing "column exists but is corrupted + many NAs".
# A clean annotation (generated by annotate_by_markers using blood_markers) should: be among the blood_markers
# types AND have a very low NA ratio. Use a dual check of "NA ratio < 50%" + "name match".
expected_types <- names(blood_markers)
valid_annotation <- "cell_type" %in% colnames(merged@meta.data) &&
  mean(is.na(merged$cell_type)) < 0.5 &&
  any(unique(na.omit(merged$cell_type)) %in% expected_types)

if (!valid_annotation) {
  cat("cell_type missing or corrupted (SCP548 raw Cell_Type / many NAs), reintegrating + re-annotating...\n")
  # Before reintegrating, free the old data/scale.data/reductions/graphs, keeping only counts,
  # otherwise NormalizeData+ScaleData would stack allocations and cause OOM (even small vectors fail).
  # These layers will all be regenerated by integrate_and_annotate, so deleting them is harmless.
  cat("  Releasing old data/scale.data/reductions/graphs (keep only counts) to free memory...\n")
  rna_layers <- merged@assays$RNA@layers
  keep <- !grepl("^(data|scale\\.data)", names(rna_layers))
  merged@assays$RNA@layers <- rna_layers[keep]
  tryCatch(merged@reductions <- list(), error = function(e) NULL)
  tryCatch(merged@graphs <- list(), error = function(e) NULL)
  rm(rna_layers, keep); gc()
  # Key: the object has ~170 split layers (one counts layer per sample),
  # and NormalizeData/ScaleData would have huge memory overhead across many layers and OOM.
  # First merge counts into a single layer before integration to greatly reduce peak memory.
  cat("  Merging ~170 split layers into a single counts layer (reduce memory overhead)...\n")
  merged <- JoinLayers(merged, assay = "RNA")
  gc()
  cat("  Remaining layers:", paste(Layers(merged[["RNA"]]), collapse = ", "), "\n")
  merged <- integrate_and_annotate(merged)
}
cat("Integrated object:", ncol(merged), "cells\n")
print(table(merged$cell_type))

## =========================================================================
## Step 2: extract the myeloid compartment
## =========================================================================

cat("\n===== Step 2: extract the myeloid compartment =====\n")

# Myeloid marker genes (verified present in the object)
myeloid_markers <- list(
  "CD14_Mono"  = c("CD14", "LYZ", "S100A8", "S100A9", "VCAN"),
  "CD16_Mono"  = c("FCGR3A", "MS4A7", "LST1", "CX3CR1"),
  "Macrophage" = c("CD68", "CD163", "MRC1", "CSF1R", "F13A1"),
  "cDC"        = c("CD1C", "CLEC10A", "HLA-DQA1", "ITGAX"),
  "pDC"        = c("LILRA4", "CLEC4C", "IL3RA", "TCF4")
)

# Free memory: subclustering will re-run NormalizeData/FVF/ScaleData/PCA/Harmony/UMAP,
# so delete scale.data from merged before subsetting.
# Key: scale.data is a 3000 HVG x 358k cells dense matrix (~8.6GB), a major memory consumer.
# (reductions/graphs are tiny, keep them so the main object still has UMAP when written back)
cat("Freeing memory (deleting scale.data dense matrix, ~8.6GB)...\n")
# Directly reassign the layers slot to delete scale.data (more reliable than [[<-, avoids copies not written back)
rna_layers <- merged@assays$RNA@layers
rna_layers[grep("scale\\.data", names(rna_layers))] <- NULL
merged@assays$RNA@layers <- rna_layers
rm(rna_layers)
gc()
cat("  Remaining layers:", paste(Layers(merged[["RNA"]]), collapse = ", "), "\n")

seu_myeloid <- subset(merged, subset = cell_type %in% c("Monocyte", "DC"))
cat("Myeloid cell count:", ncol(seu_myeloid), "\n")
print(table(seu_myeloid$cell_type, seu_myeloid$group))

# Fix Seurat v5 bug (issue #8407): after subset, the assay's @cells logical mapping may be out of sync
# (still keeps original cell count 172986), inconsistent with @meta.data (84286); subsequent NormalizeData errors with
# "Cannot add new cells with [[<-". Solution: rebuild the RNA assay (keep only counts) to force the cells
# mapping to match meta.data. data/scale.data will be regenerated in Step 3, so deleting them is harmless.
cat("Rebuilding RNA assay to fix out-of-sync cells mapping after subset...\n")
mye_counts <- GetAssayData(seu_myeloid, assay = "RNA", layer = "counts")
seu_myeloid[["RNA"]] <- CreateAssay5Object(counts = mye_counts)
rm(mye_counts); gc()
cat("  After fix cells:", ncol(seu_myeloid), " meta:", nrow(seu_myeloid@meta.data), "\n")

## =========================================================================
## Step 3: subclustering + sub-annotation
## =========================================================================

cat("\n===== Step 3: subclustering + sub-annotation (resolution = 1.0) =====\n")

old_res <- resolution
resolution <- 1.0   # Subclustering uses a higher resolution to find finer subsets
seu_myeloid <- integrate_and_annotate(seu_myeloid,
                                      marker_list = myeloid_markers,
                                      col_name = "myeloid_subtype")
resolution <- old_res

cat("\nMyeloid subsets:", paste(names(table(seu_myeloid$myeloid_subtype)),
                        collapse = ", "), "\n")
print(table(seu_myeloid$myeloid_subtype))

## =========================================================================
## Step 4: visualization validation
## =========================================================================

cat("\n===== Step 4: visualization validation =====\n")

# 4.1 UMAP: color by subtype / group / dataset
p_m1 <- DimPlot(seu_myeloid, reduction = "umap", group.by = "myeloid_subtype",
                label = TRUE, label.size = 3) + ggtitle("Myeloid Subtypes")
p_m2 <- DimPlot(seu_myeloid, reduction = "umap", group.by = "group") +
  ggtitle("Myeloid by Group")
p_m3 <- DimPlot(seu_myeloid, reduction = "umap", group.by = "dataset") +
  ggtitle("Myeloid by Dataset")
ggsave(file.path(out_dir, "path3_myeloid_UMAP.pdf"),
       plot = p_m1 | p_m2 | p_m3, width = 24, height = 8)

# 4.2 DotPlot: subset × marker genes (only plot genes present in the object)
avail_mye <- unique(unlist(lapply(myeloid_markers,
                                  function(g) intersect(g, rownames(seu_myeloid)))))
p_dot <- DotPlot(seu_myeloid, features = avail_mye, group.by = "myeloid_subtype") +
  RotatedAxis() +
  ggtitle("Myeloid Subtype Markers") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7))
ggsave(file.path(out_dir, "path3_myeloid_dotplot.pdf"),
       plot = p_dot, width = 14, height = 6)

## =========================================================================
## Step 5: five-group proportions + Ro/e
## =========================================================================

cat("\n===== Step 5: five-group proportions + Ro/e =====\n")

prop_tab <- table(seu_myeloid$myeloid_subtype, seu_myeloid$group)
prop_frac <- sweep(prop_tab, 2, colSums(prop_tab), "/")
expected <- rowSums(prop_tab) / sum(prop_tab)
roe <- sweep(prop_frac, 1, expected, "/")   # Ro/e matrix
write.csv(roe, file.path(out_dir, "path3_myeloid_roe_by_group.csv"))
cat("\nMyeloid subset Ro/e (observed/expected, >1 enriched, <1 depleted):\n")
print(round(roe, 2))

# Proportion stacked bar chart
p_prop <- ggplot(as.data.frame(prop_frac) %>%
                   rename(Subtype = Var1, Group = Var2, Frac = Freq),
                 aes(x = Group, y = Frac, fill = Subtype)) +
  geom_bar(stat = "identity", position = "fill") +
  labs(y = "Fraction", title = "Myeloid Subtype Proportion by Group") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(file.path(out_dir, "path3_myeloid_proportion.pdf"),
       plot = p_prop, width = 9, height = 6)

## =========================================================================
## Step 6: differential subset identification across groups
## =========================================================================

cat("\n===== Step 6: differential subset identification across groups =====\n")

# 6.1 Subsets enriched in each disease group relative to Healthy (Ro/e > 1.1 considered enriched)
identify_enriched <- function(roe_mat, dis_group, healthy_group = "Healthy",
                              thresh = 1.1) {
  rownames(roe_mat)[roe_mat[, dis_group] > thresh &
                      roe_mat[, healthy_group] < thresh]
}

enriched <- list(
  Infection_Control = identify_enriched(roe, "Infection_Control"),
  COPD              = identify_enriched(roe, "COPD"),
  Sepsis            = identify_enriched(roe, "Sepsis"),
  Sepsis_Pneumonia  = identify_enriched(roe, "Sepsis_Pneumonia")
)
for (nm in names(enriched)) {
  cat(sprintf("  %s enriched subsets: %s\n", nm,
              paste(enriched[[nm]], collapse = ", ")))
}

# 6.2 Comorbidity-shared enriched subsets (COPD and Sepsis both enriched)
shared_enriched <- intersect(enriched$COPD, enriched$Sepsis)
cat("\nMyeloid subsets jointly enriched in COPD and Sepsis:",
    paste(shared_enriched, collapse = ", "), "\n")

# 6.3 Sepsis-specific subsets (Sepsis enriched but Infection_Control not enriched)
sepsis_specific <- setdiff(enriched$Sepsis, enriched$Infection_Control)
cat("Sepsis-specific subsets (relative to infection control):",
    paste(sepsis_specific, collapse = ", "), "\n")

# Summary results
result_summary <- data.frame(
  subtype = rownames(roe),
  Infection_Control_roe = roe[, "Infection_Control"],
  COPD_roe = roe[, "COPD"],
  Sepsis_roe = roe[, "Sepsis"],
  Sepsis_Pneumonia_roe = roe[, "Sepsis_Pneumonia"]
)
write.csv(result_summary, file.path(out_dir, "path3_myeloid_roe_summary.csv"),
          row.names = FALSE)

## =========================================================================
## Step 7: save
## =========================================================================

cat("\n===== Step 7: save =====\n")

saveRDS(seu_myeloid, file.path(out_dir, "path3_myeloid_subclustered.rds"))

# Write the subset labels back to the main object (for later use)
merged$myeloid_subtype <- NA_character_
merged$myeloid_subtype[colnames(seu_myeloid)] <- seu_myeloid$myeloid_subtype
saveRDS(merged, file.path(out_dir, "path1_sepsis_copd_integrated.rds"))

cat("Saved:\n")
cat("  - path3_myeloid_subclustered.rds (myeloid subclustered object)\n")
cat("  - path1_sepsis_copd_integrated.rds (myeloid_subtype column written back)\n")
cat("  - path3_myeloid_roe_summary.csv (Ro/e summary per group)\n")
cat("Myeloid subset analysis complete\n")
sessionInfo()
