# =========================================================================
# 09_cellchat_communication.R
# Read the CellChat results generated by 01 (cellchat_list.rds, five groups), analyze DC-related communication:
#   1) DC total communication volume (net$weight, affected by DC cell number -> corroborates "DC exhaustion")
#   2) Key functional DC signaling ligand-receptor pairs (prob is a function of expression proportion, roughly normalized):
#        MHC-II antigen presentation (CD74/HLA-DR/DQ/DP - CD4/LAG3)
#        co-stimulation (CD80/CD86 - CD28/CTLA4)
#        DC migration (CCL19/CCL21 - CCR7)
#   observe how these key signals change across the five groups
#   (answer "whether the communication efficiency of the remaining DC cells changes")
# =========================================================================

.this_file <- tryCatch(rstudioapi::getSourceEditorContext()$path, error = function(e) "")
if (.this_file == "" || !file.exists(.this_file)) {
  .f <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(.f) > 0) .this_file <- sub("^--file=", "", .f[1])
}
SCRIPT_DIR  <- dirname(.this_file)
config_file <- file.path(SCRIPT_DIR, "00_config.R")
if (!file.exists(config_file)) stop("Cannot find 00_config.R: ", config_file)
source(config_file)

if (!requireNamespace("CellChat", quietly = TRUE)) {
  stop("CellChat is not installed, cannot perform communication analysis")
}
if (!requireNamespace("reshape2", quietly = TRUE)) {
  stop("reshape2 is not installed, please run install.packages('reshape2') first")
}
suppressPackageStartupMessages({
  library(CellChat)
  library(ggplot2)
  library(reshape2)
})

cat("\n==============================================================\n")
cat("CellChat communication analysis: DC communication volume + key ligand-receptor pairs\n")
cat("==============================================================\n")

## =========================================================================
## Step 1: read CellChat results
## =========================================================================
cc_file <- file.path(out_dir, "path1_CellChat", "cellchat_list.rds")
if (!file.exists(cc_file)) stop("Cannot find CellChat results: ", cc_file)
cc_list <- readRDS(cc_file)
cat("CellChat groups:", paste(names(cc_list), collapse = ", "), "\n")

## DC-related key functional genes (ligands/receptors)
key_modules <- list(
  "MHC-II"   = c("CD74","HLA-DRA","HLA-DRB1","HLA-DQA1","HLA-DPA1",
                 "HLA-DPB1","HLA-DMA","HLA-DMB","CD4","LAG3"),
  "Costim"   = c("CD80","CD86","CD28","CTLA4"),
  "Migration" = c("CCL19","CCL21","CCR7")
)

## =========================================================================
## Step 2: extract DC cell count + DC total communication + key L-R pair prob per group
## =========================================================================
cat("\n===== Step 2: extract DC communication =====\n")

# First determine DC cell type names (find from the first group's meta)
first_cc <- cc_list[[1]]
all_labels <- unique(as.character(first_cc@meta$labels))
dc_cells  <- all_labels[grepl("DC", all_labels)]
mono_cells <- all_labels[grepl("Mono|Monocyte", all_labels)]
cat("DC cell types:", paste(dc_cells, collapse = ", "), "\n")
cat("Monocyte cell types:", paste(mono_cells, collapse = ", "), "\n")

extract_all <- function(cc, dc_cells) {
  out <- list()
  # 1) DC cell count (after downsampling)
  labs <- as.character(cc@meta$labels)
  out$DC_ncells <- sum(labs %in% dc_cells)
  # 2) DC total communication volume (net$weight, affected by cell number)
  w <- tryCatch(as.matrix(cc@net$weight), error = function(e) matrix(0))
  rn <- rownames(w)
  dci <- which(rn %in% dc_cells)
  out$DC_out   <- if (length(dci)) sum(w[dci, , drop = FALSE]) else 0
  out$DC_in    <- if (length(dci)) sum(w[, dci, drop = FALSE]) else 0
  out$DC_total <- out$DC_out + out$DC_in
  # 3) prob of key L-R pairs (subsetCommunication)
  df <- tryCatch(subsetCommunication(cc, slot.name = "net"), error = function(e) NULL)
  out$df <- df
  out
}

res <- list()
for (g in names(cc_list)) {
  r <- extract_all(cc_list[[g]], dc_cells)
  r$group <- g
  res[[g]] <- r
  cat(" [", g, "] DC cell count:", r$DC_ncells,
      " DC_total:", round(r$DC_total, 5), "\n")
}

# Per-module DC-related prob summary
module_prob <- data.frame(group = names(res), stringsAsFactors = FALSE)
for (mod in names(key_modules)) module_prob[[mod]] <- NA_real_
module_prob$DC_ncells <- sapply(res, function(r) r$DC_ncells)
module_prob$DC_total   <- sapply(res, function(r) r$DC_total)

cat("\n===== Key L-R pair prob (involving DC) =====\n")
for (g in names(res)) {
  df <- res[[g]]$df
  if (is.null(df)) { cat(" [", g, "] subsetCommunication failed\n"); next }
  if (!"source" %in% colnames(df)) {
    cat(" [", g, "] column names:", paste(colnames(df), collapse=", "), "\n")
  }
  # Rows involving DC (source or target is DC)
  is_dc <- (df$source %in% dc_cells) | (df$target %in% dc_cells)
  df_dc <- df[is_dc, , drop = FALSE]
  for (mod in names(key_modules)) {
    genes <- key_modules[[mod]]
    hit <- (df_dc$ligand %in% genes) | (df_dc$receptor %in% genes)
    if (any(hit)) {
      module_prob[[mod]][module_prob$group == g] <- sum(df_dc$prob[hit])
    } else {
      module_prob[[mod]][module_prob$group == g] <- 0
    }
  }
  # Print key L-R pair details (top)
  hit_all <- (df_dc$ligand %in% unlist(key_modules)) |
             (df_dc$receptor %in% unlist(key_modules))
  if (any(hit_all)) {
    sub <- df_dc[hit_all, , drop = FALSE]
    sub <- sub[order(-sub$prob), , drop = FALSE]
    sub <- head(sub, 6)
    cat(" [", g, "] key L-R pairs (top6):\n")
    for (i in seq_len(nrow(sub))) {
      cat(sprintf("     %s -> %s : %s-%s, prob=%.4f\n",
                  sub$source[i], sub$target[i], sub$ligand[i],
                  sub$receptor[i], sub$prob[i]))
    }
  }
}
print(module_prob)
write.csv(module_prob, file.path(out_dir, "path9_dc_key_lr_prob.csv"), row.names = FALSE)

## =========================================================================
## Step 3: normalize communication strength (per DC cell)
## =========================================================================
cat("\n===== Step 3: normalization (per DC cell) =====\n")

norm <- module_prob
for (col in names(key_modules)) {
  norm[[paste0(col, "_perDC")]] <- norm[[col]] / norm$DC_ncells
}
norm$DC_total_perDC <- norm$DC_total / norm$DC_ncells
print(norm[, c("group", "DC_ncells", "DC_total", "DC_total_perDC",
               paste0(names(key_modules), "_perDC"))])
write.csv(norm, file.path(out_dir, "path9_dc_norm_comm.csv"), row.names = FALSE)

## =========================================================================
## Step 4: visualization
## =========================================================================
cat("\n===== Step 4: visualization =====\n")

# Drop the empty Migration panel (CCL19/CCL21 ligands are not expressed in peripheral blood,
# CellChat L-R pairs get filtered by filterCommunication(min.cells=10), always 0)
plot_mods <- setdiff(names(key_modules), "Migration")

# Group order consistent with main figures (Healthy -> Infection_Control -> COPD -> Sepsis -> Sepsis_Pneumonia)
grp_levels <- c("Healthy", "Infection_Control", "COPD", "Sepsis", "Sepsis_Pneumonia")
# 2026-09-05: uniformly use the main-figure color scheme (Fig. S4 / Fig. 2 etc.) to avoid inconsistent default hues across figures
grp_cols <- c(Healthy = "#3C5488", Infection_Control = "#91D1C2",
              COPD = "#00A087", Sepsis = "#E64B35",
              Sepsis_Pneumonia = "#F39B7F")
module_prob$group <- factor(module_prob$group, levels = grp_levels)
norm$group <- factor(norm$group, levels = grp_levels)

# Key L-R pair prob bar chart (by module)
ml <- reshape2::melt(module_prob[, c("group", plot_mods)],
                     id.vars = "group", variable.name = "module",
                     value.name = "prob")
p1 <- ggplot(ml, aes(x = group, y = prob, fill = group)) +
  geom_col(alpha = 0.85) +
  facet_wrap(~ module, scales = "free_y") +
  scale_fill_manual(values = grp_cols, guide = "none") +
  labs(title = "DC key L-R pair prob (5 groups)", y = "prob sum") +
  theme_bw(base_size = 11) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), legend.position = "none")
ggsave(file.path(out_dir, "path9_dc_key_lr_prob.pdf"), p1, width = 9, height = 5)

# Per-DC-cell normalized communication
nl <- reshape2::melt(norm[, c("group", paste0(plot_mods, "_perDC"))],
                     id.vars = "group", variable.name = "module",
                     value.name = "prob_perDC")
p2 <- ggplot(nl, aes(x = group, y = prob_perDC, fill = group)) +
  geom_col(alpha = 0.85) +
  facet_wrap(~ module, scales = "free_y") +
  scale_fill_manual(values = grp_cols, guide = "none") +
  labs(title = "Communication strength per DC cell (normalized)", y = "prob / DC count") +
  theme_bw(base_size = 11) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), legend.position = "none")
ggsave(file.path(out_dir, "path9_dc_norm_comm.pdf"), p2, width = 9, height = 5)

cat("\nCellChat communication analysis complete\n")
cat("Output: path9_dc_key_lr_prob.csv / path9_dc_norm_comm.csv /\n")
cat("      path9_dc_key_lr_prob.pdf / path9_dc_norm_comm.pdf\n")
cat("Interpretation: prob is a function of expression proportion (roughly normalized), compare key module prob directly;\n")
cat("      if the MHC-II/Costim/Migration prob in Sepsis/COPD is instead elevated,\n")
cat("      it indicates 'compensatory enhancement of remaining DC communication function'\n")
